-- Supabase / PostgreSQL schema for the TraceLink Field Log
-- Run this once in the Supabase SQL Editor.

create table if not exists public.entries (
  entry_date date primary key,
  tasks jsonb not null default '[]'::jsonb,
  goals jsonb not null default '[]'::jsonb,
  hours numeric not null default 0,
  status text not null default 'on-track',
  notes text not null default '',
  learning text not null default '',
  idea text not null default '',
  reflection text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.manager_notes (
  id bigint generated by default as identity primary key,
  week_start date not null,
  text text not null,
  author text not null default 'Manager',
  created_at timestamptz not null default now()
);

create index if not exists manager_notes_week_start_idx
  on public.manager_notes (week_start);

-- This app uses the Supabase service-role key on the server side.
-- Do NOT expose that key in client-side code.
-- If you later replace the app's password gate with Supabase Auth,
-- add Row Level Security policies appropriate to your users.
