create table if not exists public.entries (
  entry_date date primary key,
  tasks jsonb not null default '[]'::jsonb,
  goals text not null default '',
  hours numeric not null default 0,
  status text not null default 'on-track',
  notes text not null default '',
  learning text not null default '',
  idea text not null default '',
  reflection text not null default '',
  private boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.manager_notes (
  id bigint generated by default as identity primary key,
  week_start date not null,
  text text not null,
  author text not null default 'Manager',
  created_at timestamptz not null default now()
);

create index if not exists manager_notes_week_start_idx
on public.manager_notes (week_start);

-- Existing deployments can keep goals as TEXT: the app stores the bullet list
-- as newline-separated '- item' lines and renders each line as a bullet.
